development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: products_searcher_development
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: products_searcher_test
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING
