modules:
  - name: "products_searcher"
    exclude: ['jquery', 'underscore', 'backbone']
  - name: "application"
  - name: "jquery"
  - name: "underscore"
  - name: "backbone"
    exclude: ['jquery', 'underscore']
  - name: "epoxy"
    exclude: ['underscore', 'jquery', 'backbone']
  - name: "bootstrap/bootstrap-typeahead"
    exclude: ['jquery']
  - name: "routers/router"
    exclude: ['jquery', 'underscore', 'backbone']
  - name: "models/product"
    exclude: ['jquery', 'underscore', 'backbone']
  - name: "collections/products"
    exclude: ['jquery', 'underscore', 'backbone', 'models/product']
  - name: "views/shops/add_products"
    exclude: ['jquery', 'underscore', 'backbone']
  - name: "views/products/product_price"
    exclude: ['jquery', 'underscore', 'backbone']
  - name: "products/product_price_tmpl"

paths:
  application: 'application'
  jquery-min: 'jquery'
  jquery-ujs: 'jquery_ujs'
  backbone: 'backbone'
  underscore: 'underscore'
  epoxy: 'epoxy'

shim:
  backbone:
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  underscore:
    exports: '_'
  bootstrap-typeahead:
    deps: ['jquery']
    exports: '$.fn.typeahead'
  epoxy:
    deps: ['underscore', 'jquery', 'backbone']
    exports: 'Epoxy'
